# Generated by Django 4.1 on 2022-08-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Категоря')),
                ('slug', models.SlugField(max_length=300, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SellThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя владельца продаваемого товара')),
                ('thing', models.CharField(max_length=300, verbose_name='Название продаваемого товара')),
                ('foto', models.ImageField(blank=True, upload_to='photos_sell_thing/%Y', verbose_name='Фото')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('passport', models.TextField(verbose_name='Паспортные данные')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('time_safe', models.DateField(verbose_name='Время появления у вас этой вещи')),
                ('place', models.CharField(max_length=300, verbose_name='Место хранения этой вещи')),
                ('defect_out', models.CharField(max_length=300, verbose_name='Повреждения внешние')),
                ('defect_in', models.CharField(max_length=300, verbose_name='Работоспособность продаваемого устройства')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличие')),
                ('numbers_thing', models.IntegerField(verbose_name='Количество устройств')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продажа вещи',
                'verbose_name_plural': 'Продажа вещей',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, verbose_name='URL')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('foto', models.ImageField(blank=True, upload_to='photos/%Y', verbose_name='Фото')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_available', models.BooleanField(default=False, verbose_name='Есть в наличие')),
                ('col', models.IntegerField(verbose_name='Количество')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
                'ordering': ['-time'],
            },
        ),
    ]
